[build]
builder = "nixpacks"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["dotnet-sdk"]

[build.nixpacksPlan.variables]
DOTNET_VERSION = "10"

[deploy]
startCommand = "cd out && dotnet SystemMonitorApp.dll"